name: test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: kintone/rest
          # path: repo-a
      # - uses: actions/checkout@v4
      #   with:
      #     repository: kintone/rest
      #     path: repo-b
      - run: ls -la
