name: test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: chihiro-adachi/branch-rules
          path: branch-rules

      - run: ls -la
      - run: ls -la branch-rules
